### PR TITLE
Add RecordType to objects_without_is_deleted

### PR DESCRIPTION
**Pull request by mostafa-anm**

### CODE REVIEW

**Comment by mostafa-anm** [comment]
@samifahed spell check failed, will fix and reassign

**Comment by codingjoe** [comment]
@mostafa-anm really good work, thanks!

**Comment by codingjoe** [comment]
@mostafa-anm if you rebase the docs will build again :)

**Comment by mostafa-anm** [comment]
rebased and added recordtype to warning.

tests for spellcheck still failing

**Pull request merged**
