### PR TITLE
Set isort line_length to 99 to match with pycodestyle rule

### PR DESCRIPTION
**Pull request by amureki**
I noticed, that there is an inconsistency in isort and pycodestyle rules, so this PR fixes that.

### CODE REVIEW

**Comment by codingjoe** [comment]
Let me quickly explain why we increased the soft wrap limit form 79 chars to 99 chars. We did increase the limit to avoid more hanging indentation or other weird constructs than necessary.
We all have pretty big screens these days. So there are some cases where it just makes more sense to write a longer line to improve readablity. Never the less, 79 char wraps are a good idea.

Imports are, at least in our case auto sorted and generated. PyCharm hides them in the code view by default and in any case I don't consider part of the code. That being said, does your change improve readability and does it even matter?

**Comment by amureki** [comment]
@codingjoe thank you for the explanation!

My thoughts here - imports are still part of the code. Even if Pycharm hides it by default (which I don't have), it is still there, and I guess, should follow same rules as the rest of the code. Also, definitely, not everyone is using Pycharm. :) In our company we have Vscode, and maybe something else. I even remember somebody was using vim, so you cannot expect to have hidden imports from everyone.
Also, it is, of course, a question of taste, and for me, since we are fine with 99 in the codebase, then I would like to avoid constructions like this if we can:
```
from django.db.models.fields.related import (
    ForeignKey, ManyToManyField, RelatedField
)
```

In any case, yes, imports are being sorted by `isort`, so we are not really worrying about it, that is true. So, I don't see this change as making it worse, only better (at least in terms of consistency).

**Comment by codingjoe** [comment]
@amureki I didn't want to make this about imports being part of the code or not. The important note from my side is, the recommended line limit is 79 chars + soft wrap. It's not 99. That also why all our plain texts have are wrapped at 79 chars. Because you can hardly make an argument for better readablity of a regular text for a given line.

I am happy to be convinced but currently I fail to see why imports should break the norm.

**Comment by amureki** [comment]
@codingjoe 
Okay, I was not aware of soft wrap of 20 characters.

Plain texts, javascript, configs are different, our scope here is only a python code, to which imports are absolutely related. :)

But it is more a question of taste then, I feel them having the same rules (soft and hard) as rest part of the python codebase. That's why I made this proposal.

So it is up to you, feel free to close it!

**Comment by codingjoe** [comment]
Let's take the discussion into the team meeting. I am happy to increase the line length.

**Comment by amureki** [comment]
@codingjoe sure, that would be the best option! 🥇

**Comment by amureki** [comment]
@codingjoe hi, what about just removing the line about the `line_length` from config as we discussed? Would we be fine in the public packages with that?

**Pull request merged**
