### PR TITLE
Switch to datetime

### PR DESCRIPTION
**Pull request by grant0711**

### CODE REVIEW

**Comment by grant0711** [comment]
Fix for issue: https://github.com/thermondo/django-heroku-connect/issues/121

**Comment by grant0711** [comment]
I don't know the rules of your flow here- should this utilize django42 as base instead of master?

**Comment by syphar** [comment]
> I don't know the rules of your flow here- should this utilize django42 as base instead of master?

thanks for asking! I imagined it exactly like you did it, fixing it on master. 

Let's see what the test-suite says :)

**Comment by syphar** [comment]
Thank you for the fix! 

- the bandit failure is already fixed in #123, so a rebase on master should fix them. 
- the codecov issues come from secret usage, I quickly removed reporting coverage from forks in b9a992d4ce74c582b5855028f611f37a34c198e2 . 

So, could you rebase on master? Then we can see if the test-suite passes fully

**Comment by grant0711** [comment]
Great, thank you! Just merged master into this branch to bring in those commits.

**Review by syphar — APPROVED** [review]

**Pull request merged**
