### PR TITLE
drop EOL python 3.8

### PR DESCRIPTION
**Pull request by syphar**
see https://devguide.python.org/versions/

### CODE REVIEW

**Review by zahidkizmaz — COMMENTED** [review]
should we also bump the version in pyproject.toml?

**Comment by syphar** [comment]
> should we also bump the version in pyproject.toml?

good catch, missed tha

**Comment by syphar** [comment]
The linter errors are fixed in #200

**Review by zahidkizmaz — APPROVED** [review]
looks good thank you!

**Pull request merged**
